AWSTemplateFormatVersion: 2010-09-09
Description: "Security Groups for SSH Access (Specific IPs) and Internet-Facing ALB"

Parameters:
  OpsAllowedIP1:
    Type: String
    Description: "Michelle WS Home"
  OpsAllowedIP2:
    Type: String
    Description: "Michelle WS Home 2"
  OpsAllowedIP3:
    Type: String
    Description: "Nick Home 2"
  OpsAllowedIP4:
    Type: String
    Description: "Troy WS Home"
  OpsAllowedIP5:
    Type: String
    Description: "WS Office"
  OpsAllowedIP6:
    Type: String
    Description: "Cindy WS Home"
  OpsAllowedIP7:
    Type: String
    Description: "Tin WS Home"
  OpsAllowedIP8:
    Type: String
    Description: "Nick WS Home"
  OpsAllowedIP9:
    Type: String
    Description: "Wale WS Home"
  OpsAllowedIP10:
    Type: String
    Description: "OPENVPN Access"
  OpsAllowedIP11:
    Type: String
    Description: "Chris WS Home"

Resources:
  OpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows SSH access only from specific IPs"
      VpcId: !ImportValue networking-VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP1}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP2}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP3}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP4}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP5}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP6}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP7}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP8}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP9}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP10}/32"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${OpsAllowedIP11}/32"
      Tags:
        - Key: Name
          Value: "SSH_ACCESS"

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows HTTP/HTTPS traffic from anywhere"
      VpcId: !ImportValue networking-VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: "INTERNET_FACING_ALB"

Outputs:
  OpsSecurityGroupId:
    Description: "Security Group ID for SSH Access"
    Value: !Ref OpsSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-OpsSecurityGroupId"

  AlbSecurityGroupId:
    Description: "Security Group ID for Internet-Facing ALB"
    Value: !Ref AlbSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-AlbSecurityGroupId"