AWSTemplateFormatVersion: 2010-09-09
Description: "Security Groups for SSH Access (Specific IPs) and Internet-Facing ALB"

Parameters:
  SshAccessAllowedIP1:
    Type: String
    Description: "Michelle WS Home"
  SshAccessAllowedIP2:
    Type: String
    Description: "Michelle WS Home 2"
  SshAccessAllowedIP3:
    Type: String
    Description: "Nick Home 2"
  SshAccessAllowedIP4:
    Type: String
    Description: "Troy WS Home"
  SshAccessAllowedIP5:
    Type: String
    Description: "WS Office"
  SshAccessAllowedIP6:
    Type: String
    Description: "Cindy WS Home"
  SshAccessAllowedIP7:
    Type: String
    Description: "Tin WS Home"
  SshAccessAllowedIP8:
    Type: String
    Description: "Nick WS Home"
  SshAccessAllowedIP9:
    Type: String
    Description: "Wale WS Home"
  SshAccessAllowedIP10:
    Type: String
    Description: "OPENVPN Access"
  SshAccessAllowedIP11:
    Type: String
    Description: "Chris WS Home"

Resources:
  SshAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows SSH access only from specific IPs"
      VpcId: !ImportValue networking-VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP1}/32"
          Description: "Michelle WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP2}/32"
          Description: "Michelle WS Home 2"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP3}/32"
          Description: "Nick Home 2"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP4}/32"
          Description: "Troy WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP5}/32"
          Description: "WS Office"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP6}/32"
          Description: "Cindy WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP7}/32"
          Description: "Tin WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP8}/32"
          Description:  "Nick WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP9}/32"
          Description: "Wale WS Home"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP10}/32"
          Description: "OPENVPN Access"
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: !Sub "${SshAccessAllowedIP11}/32"
          Description: "Chris WS Home"
      Tags:
        - Key: Name
          Value: "SSH_ACCESS"

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allows HTTP/HTTPS traffic from anywhere"
      VpcId: !ImportValue networking-VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
          Description: "Allows HTTP traffic"
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
          Description: "Allows HTTPS traffic"
      Tags:
        - Key: Name
          Value: "INTERNET_FACING_ALB"
  SwarmManagerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Docker Swarm Managers"
      VpcId: !ImportValue networking-VPCId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 2377
          ToPort: 2377
          SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
          Description: "Allows worker nodes to communicate with manager nodes"
        - IpProtocol: "tcp"
          FromPort: 7946
          ToPort: 7946
          SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
          Description: "Allows TCP-based intra-cluster communication between Swarm nodes"
        - IpProtocol: udp
          FromPort: 7946
          ToPort: 7946
          SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
          Description: "Allows UDP-based intra-cluster communication between Swarm nodes"
        - IpProtocol: udp
          FromPort: 4789
          ToPort: 4789
          SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
          Description: "Allows overlay network traffic for Swarm service"
      Tags:
        - Key: Name
          Value: "DOCKER_SWARM_MANAGER"

  SwarmWorkerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Docker Swarm Workers"
      VpcId: !ImportValue networking-VPCId
      Tags:
        - Key: Name
          Value: "DOCKER_SWARM_WORKER"

  SwarmWorkerToManagerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmManagerSecurityGroup
      IpProtocol: tcp
      FromPort: 7946
      ToPort: 7946
      SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
      Description: "Allows TCP communication from workers to managers"

  SwarmWorkerToManagerIngressUDP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmManagerSecurityGroup
      IpProtocol: udp
      FromPort: 7946
      ToPort: 7946
      SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
      Description: "Allows UDP communication from workers to managers"

  SwarmWorkerToManagerOverlayNetwork:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmManagerSecurityGroup
      IpProtocol: udp
      FromPort: 4789
      ToPort: 4789
      SourceSecurityGroupId: !Ref SwarmWorkerSecurityGroup
      Description: "Allows overlay network traffic from workers to managers"

  SwarmManagerToWorkerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmWorkerSecurityGroup
      IpProtocol: tcp
      FromPort: 7946
      ToPort: 7946
      SourceSecurityGroupId: !Ref SwarmManagerSecurityGroup
      Description: "Allows TCP communication from managers to workers"

  SwarmManagerToWorkerIngressUDP:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmWorkerSecurityGroup
      IpProtocol: udp
      FromPort: 7946
      ToPort: 7946
      SourceSecurityGroupId: !Ref SwarmManagerSecurityGroup
      Description: "Allows UDP communication from managers to workers"

  SwarmManagerToWorkerOverlayNetwork:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SwarmWorkerSecurityGroup
      IpProtocol: udp
      FromPort: 4789
      ToPort: 4789
      SourceSecurityGroupId: !Ref SwarmManagerSecurityGroup
      Description: "Allows overlay network traffic from managers to workers"
  

Outputs:
  SshAccessSecurityGroupId:
    Description: "Security Group ID for SSH Access"
    Value: !Ref SshAccessSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SshAccessSecurityGroupId"

  AlbSecurityGroupId:
    Description: "Security Group ID for Internet-Facing ALB"
    Value: !Ref AlbSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-AlbSecurityGroupId"
  
  SwarmManagerSecurityGroupId:
    Description: "Security Group ID for Swarm Manager"
    Value: !Ref SwarmManagerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SwarmManagerSecurityGroupId"
  
  SwarmWorkerSecurityGroupId:
    Description: "ID of the Swarm Worker Security Group"
    Value: !Ref SwarmWorkerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SwarmWorkerSecurityGroupId"
