name: Deploy Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Deploy Dev Environment
        run: |
          chmod +x deployment/deploy-stack.sh
          ./deployment/deploy-stack.sh networking
          #./deployment/deploy-stack.sh security
